server:
  port: 2003
spring:
  application:
    name: seata-account
  cloud:
    nacos:
      discovery:
        server-addr: www.cchili.xyz:8848
    alibaba:
      seata:
        tx-service-group: song_tx_group
  datasource:
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
