spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称
      routes:
        - id: method_route
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的地址
          predicates:
            - Method=GET,POST
            - After=2020-06-19T22:03:30.388+08:00[Asia/Shanghai]
#            - Cookie=username,song
