server:
  port: 8001

spring:
  application:
    name: alibaba-provide-payment
  cloud:
    nacos:
      discovery:
        server-addr: www.cchili.xyz:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
