server:
  port: 80

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: cloud-consumer-payment
