server:
  port: 80

#eureka
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: cloud-consumer-payment
